import {
  Student,
  Teacher,
  ClassRoom,
  Subject,
  AttendanceRecord,
  Exam,
  ExamMark,
  FeeInvoice,
  TimetableSlot,
  Announcement,
  CourseProgram,
  Testimonial,
  SchoolSettings
} from '../types';

export const INITIAL_SCHOOL_SETTINGS: SchoolSettings = {
  institutionName: 'EduFlow Academy of Excellence',
  tagline: 'Empowering Next-Generation Scholars through Intelligent Education',
  logoUrl: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?auto=format&fit=crop&w=120&q=80',
  academicYear: '2025 - 2026',
  email: 'admissions@eduflow.edu',
  phone: '+1 (800) 555-EDUSIS',
  address: '100 University Heights Parkway, Tech City, CA 94107',
  gradingScale: '4.0 Scale (A+, A, B, C, D, F)',
  enableNotifications: true,
};

export const SAMPLE_CLASSES: ClassRoom[] = [
  { id: 'cls-1', name: 'Grade 10-A', gradeLevel: '10th Grade', section: 'A', capacity: 35, studentCount: 28, classTeacherName: 'Dr. Robert Vance', roomNumber: 'Lab 201' },
  { id: 'cls-2', name: 'Grade 10-B', gradeLevel: '10th Grade', section: 'B', capacity: 35, studentCount: 30, classTeacherName: 'Prof. Sarah Jenkins', roomNumber: 'Room 204' },
  { id: 'cls-3', name: 'Grade 11-Science', gradeLevel: '11th Grade', section: 'Sci', capacity: 40, studentCount: 36, classTeacherName: 'Dr. Alan Turing', roomNumber: 'Science Hall 1' },
  { id: 'cls-4', name: 'B.Tech CS - Year 2', gradeLevel: 'Undergraduate', section: 'CS-A', capacity: 45, studentCount: 42, classTeacherName: 'Dr. Elena Rostova', roomNumber: 'Tech Annex 3B' },
  { id: 'cls-5', name: 'B.Sc Data Science', gradeLevel: 'Undergraduate', section: 'DS-1', capacity: 30, studentCount: 25, classTeacherName: 'Prof. Marcus Brody', roomNumber: 'Analytics Lab' },
];

export const SAMPLE_SUBJECTS: Subject[] = [
  { id: 'sub-1', code: 'CS201', name: 'Data Structures & Algorithms', department: 'Computer Science', credits: 4, description: 'Fundamental concepts of linear & non-linear data structures, trees, graphs, sorting, and complexity.' },
  { id: 'sub-2', code: 'MATH301', name: 'Advanced Applied Calculus', department: 'Mathematics', credits: 3, description: 'Multivariable calculus, vector analysis, linear algebra applications, and differential equations.' },
  { id: 'sub-3', code: 'PHY102', name: 'Quantum & Wave Physics', department: 'Physics', credits: 4, description: 'Principles of wave mechanics, quantum theory, semiconductor physics, and laser optics.' },
  { id: 'sub-4', code: 'ENG205', name: 'Technical & Professional Communication', department: 'Humanities', credits: 2, description: 'Modern business writing, research paper methodology, oral presentation, and tech reporting.' },
  { id: 'sub-5', code: 'AI401', name: 'Machine Learning Foundations', department: 'Computer Science', credits: 4, description: 'Supervised/unsupervised learning, neural networks, decision trees, and model optimization.' },
];

export const SAMPLE_STUDENTS: Student[] = [
  {
    id: 'std-101',
    rollNumber: 'EDU-2026-001',
    firstName: 'Alexander',
    lastName: 'Wright',
    email: 'alex.wright@student.eduflow.edu',
    classId: 'cls-4',
    className: 'B.Tech CS - Year 2',
    section: 'CS-A',
    gender: 'Male',
    dateOfBirth: '2005-04-12',
    parentName: 'Marcus Wright',
    parentPhone: '+1 (555) 234-5678',
    parentEmail: 'marcus.wright@gmail.com',
    address: '742 Evergreen Terrace, Tech Valley',
    bloodGroup: 'O+',
    enrollmentDate: '2024-08-15',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
    gpa: 3.88,
    attendancePercentage: 96.4,
  },
  {
    id: 'std-102',
    rollNumber: 'EDU-2026-002',
    firstName: 'Sophia',
    lastName: 'Chen',
    email: 'sophia.chen@student.eduflow.edu',
    classId: 'cls-4',
    className: 'B.Tech CS - Year 2',
    section: 'CS-A',
    gender: 'Female',
    dateOfBirth: '2005-09-21',
    parentName: 'David Chen',
    parentPhone: '+1 (555) 345-6789',
    parentEmail: 'dchen.tech@gmail.com',
    address: '128 Willow Creek Way, Suite 4B',
    bloodGroup: 'A+',
    enrollmentDate: '2024-08-15',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=250&q=80',
    gpa: 3.95,
    attendancePercentage: 98.2,
  },
  {
    id: 'std-103',
    rollNumber: 'EDU-2026-003',
    firstName: 'Lucas',
    lastName: 'Moreno',
    email: 'lucas.moreno@student.eduflow.edu',
    classId: 'cls-1',
    className: 'Grade 10-A',
    section: 'A',
    gender: 'Male',
    dateOfBirth: '2008-11-05',
    parentName: 'Elena Moreno',
    parentPhone: '+1 (555) 456-7890',
    parentEmail: 'elena.moreno@yahoo.com',
    address: '409 Horizon Blvd, Bay Area',
    bloodGroup: 'B+',
    enrollmentDate: '2023-09-01',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80',
    gpa: 3.65,
    attendancePercentage: 92.0,
  },
  {
    id: 'std-104',
    rollNumber: 'EDU-2026-004',
    firstName: 'Emma',
    lastName: 'Watson',
    email: 'emma.watson@student.eduflow.edu',
    classId: 'cls-3',
    className: 'Grade 11-Science',
    section: 'Sci',
    gender: 'Female',
    dateOfBirth: '2007-03-18',
    parentName: 'Richard Watson',
    parentPhone: '+1 (555) 567-8901',
    parentEmail: 'rwatson@outlook.com',
    address: '89 Maple Ridge Court',
    bloodGroup: 'AB+',
    enrollmentDate: '2023-09-01',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=250&q=80',
    gpa: 3.72,
    attendancePercentage: 94.8,
  },
  {
    id: 'std-105',
    rollNumber: 'EDU-2026-005',
    firstName: 'Aarav',
    lastName: 'Patel',
    email: 'aarav.patel@student.eduflow.edu',
    classId: 'cls-5',
    className: 'B.Sc Data Science',
    section: 'DS-1',
    gender: 'Male',
    dateOfBirth: '2004-06-30',
    parentName: 'Sanjay Patel',
    parentPhone: '+1 (555) 678-9012',
    parentEmail: 'sanjay.patel@biotech.com',
    address: '512 Oakwood Avenue',
    bloodGroup: 'O-',
    enrollmentDate: '2024-08-15',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=250&q=80',
    gpa: 3.82,
    attendancePercentage: 95.5,
  },
];

export const SAMPLE_TEACHERS: Teacher[] = [
  {
    id: 'tch-201',
    employeeId: 'EMP-T-01',
    firstName: 'Dr. Elena',
    lastName: 'Rostova',
    email: 'elena.rostova@faculty.eduflow.edu',
    phone: '+1 (555) 111-2233',
    department: 'Computer Science',
    qualification: 'Ph.D. in Computer Science (MIT)',
    subjects: ['CS201', 'AI401'],
    assignedClassId: 'cls-4',
    assignedClassName: 'B.Tech CS - Year 2',
    joiningDate: '2019-07-01',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=250&q=80',
  },
  {
    id: 'tch-202',
    employeeId: 'EMP-T-02',
    firstName: 'Dr. Robert',
    lastName: 'Vance',
    email: 'robert.vance@faculty.eduflow.edu',
    phone: '+1 (555) 222-3344',
    department: 'Mathematics',
    qualification: 'Ph.D. in Applied Mathematics (Stanford)',
    subjects: ['MATH301'],
    assignedClassId: 'cls-1',
    assignedClassName: 'Grade 10-A',
    joiningDate: '2018-08-15',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=250&q=80',
  },
  {
    id: 'tch-203',
    employeeId: 'EMP-T-03',
    firstName: 'Prof. Sarah',
    lastName: 'Jenkins',
    email: 'sarah.jenkins@faculty.eduflow.edu',
    phone: '+1 (555) 333-4455',
    department: 'Physics',
    qualification: 'M.Sc. Physics (Oxford University)',
    subjects: ['PHY102'],
    assignedClassId: 'cls-2',
    assignedClassName: 'Grade 10-B',
    joiningDate: '2020-01-10',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=250&q=80',
  },
  {
    id: 'tch-204',
    employeeId: 'EMP-T-04',
    firstName: 'Prof. Marcus',
    lastName: 'Brody',
    email: 'marcus.brody@faculty.eduflow.edu',
    phone: '+1 (555) 444-5566',
    department: 'Humanities & Comms',
    qualification: 'M.A. Linguistics & Journalism (Columbia)',
    subjects: ['ENG205'],
    assignedClassId: 'cls-5',
    assignedClassName: 'B.Sc Data Science',
    joiningDate: '2021-09-01',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=250&q=80',
  },
];

export const SAMPLE_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-1',
    title: 'Spring 2026 Mid-Term Examination Schedule Released',
    content: 'The official timetable for Mid-Term examinations has been published. All students are advised to check their exam portal and download their hall tickets before March 1, 2026.',
    date: '2026-02-10',
    authorName: 'Academic Registrar Office',
    authorRole: 'Admin',
    targetAudience: 'All',
    priority: 'High',
    category: 'Exam',
    isPinned: true,
  },
  {
    id: 'ann-2',
    title: 'Annual EduTech Hackathon & AI Innovation Summit',
    content: 'Registration is now open for our annual institution-wide hackathon. Cash prizes total $15,000 for top projects in AI, Sustainability, and FinTech.',
    date: '2026-02-08',
    authorName: 'Dr. Elena Rostova',
    authorRole: 'Department Head',
    targetAudience: 'Students',
    priority: 'Medium',
    category: 'Event',
    isPinned: true,
  },
  {
    id: 'ann-3',
    title: 'Parent-Teacher Consultations & Academic Progress Meet',
    content: 'We invite all parents to join our virtual/in-person progress meeting on February 20th to discuss mid-semester performance and career counseling.',
    date: '2026-02-05',
    authorName: 'Principal Office',
    authorRole: 'Admin',
    targetAudience: 'Parents',
    priority: 'High',
    category: 'General',
    isPinned: false,
  },
  {
    id: 'ann-4',
    title: 'Faculty Workshop: Implementing AI Tools in Curriculum',
    content: 'A mandatory professional learning workshop for all teaching staff on integrating generative AI tools and adaptive assessment techniques.',
    date: '2026-02-02',
    authorName: 'Dean of Academics',
    authorRole: 'Admin',
    targetAudience: 'Teachers',
    priority: 'Medium',
    category: 'Academic',
    isPinned: false,
  },
];

export const SAMPLE_EXAMS: Exam[] = [
  { id: 'ex-1', title: 'Data Structures Mid-Term', term: 'Mid-Term', classId: 'cls-4', className: 'B.Tech CS - Year 2', subjectId: 'sub-1', subjectName: 'Data Structures & Algorithms', examDate: '2026-03-05', startTime: '09:30 AM', endTime: '12:30 PM', maxMarks: 100, passingMarks: 40 },
  { id: 'ex-2', title: 'Calculus Advanced Quiz 2', term: 'Quiz', classId: 'cls-4', className: 'B.Tech CS - Year 2', subjectId: 'sub-2', subjectName: 'Advanced Applied Calculus', examDate: '2026-03-08', startTime: '02:00 PM', endTime: '04:00 PM', maxMarks: 50, passingMarks: 20 },
  { id: 'ex-3', title: 'Quantum Physics Spring Final', term: 'Final', classId: 'cls-3', className: 'Grade 11-Science', subjectId: 'sub-3', subjectName: 'Quantum & Wave Physics', examDate: '2026-03-12', startTime: '10:00 AM', endTime: '01:00 PM', maxMarks: 100, passingMarks: 40 },
];

export const SAMPLE_MARKS: ExamMark[] = [
  { id: 'mrk-1', examId: 'ex-1', studentId: 'std-101', studentName: 'Alexander Wright', rollNumber: 'EDU-2026-001', subjectName: 'Data Structures & Algorithms', marksObtained: 92, maxMarks: 100, grade: 'A+', remarks: 'Exceptional algorithm complexity analysis' },
  { id: 'mrk-2', examId: 'ex-1', studentId: 'std-102', studentName: 'Sophia Chen', rollNumber: 'EDU-2026-002', subjectName: 'Data Structures & Algorithms', marksObtained: 98, maxMarks: 100, grade: 'A+', remarks: 'Top score in class! Perfect code implementation' },
  { id: 'mrk-3', examId: 'ex-2', studentId: 'std-101', studentName: 'Alexander Wright', rollNumber: 'EDU-2026-001', subjectName: 'Advanced Applied Calculus', marksObtained: 44, maxMarks: 50, grade: 'A', remarks: 'Great matrix transformation logic' },
  { id: 'mrk-4', examId: 'ex-3', studentId: 'std-104', studentName: 'Emma Watson', rollNumber: 'EDU-2026-004', subjectName: 'Quantum & Wave Physics', marksObtained: 89, maxMarks: 100, grade: 'A', remarks: 'Very thorough derivations' },
];

export const SAMPLE_FEES: FeeInvoice[] = [
  { id: 'fee-101', invoiceNumber: 'INV-2026-8801', studentId: 'std-101', studentName: 'Alexander Wright', className: 'B.Tech CS - Year 2', rollNumber: 'EDU-2026-001', title: 'Spring 2026 Tuition Fee', amount: 2400, paidAmount: 2400, dueDate: '2026-01-31', status: 'Paid', paymentDate: '2026-01-20', paymentMethod: 'Credit Card', category: 'Tuition' },
  { id: 'fee-102', invoiceNumber: 'INV-2026-8802', studentId: 'std-102', studentName: 'Sophia Chen', className: 'B.Tech CS - Year 2', rollNumber: 'EDU-2026-002', title: 'Spring 2026 Tuition Fee', amount: 2400, paidAmount: 2400, dueDate: '2026-01-31', status: 'Paid', paymentDate: '2026-01-18', paymentMethod: 'Bank Transfer', category: 'Tuition' },
  { id: 'fee-103', invoiceNumber: 'INV-2026-8803', studentId: 'std-103', studentName: 'Lucas Moreno', className: 'Grade 10-A', rollNumber: 'EDU-2026-003', title: 'Lab & Science Activity Fee', amount: 650, paidAmount: 300, dueDate: '2026-02-28', status: 'Partial', paymentDate: '2026-02-01', paymentMethod: 'UPI', category: 'Lab' },
  { id: 'fee-104', invoiceNumber: 'INV-2026-8804', studentId: 'std-104', studentName: 'Emma Watson', className: 'Grade 11-Science', rollNumber: 'EDU-2026-004', title: 'Annual Transport & Sports Pass', amount: 800, paidAmount: 0, dueDate: '2026-02-15', status: 'Pending', category: 'Transport' },
];

export const SAMPLE_TIMETABLE: TimetableSlot[] = [
  { id: 'tt-1', classId: 'cls-4', className: 'B.Tech CS - Year 2', dayOfWeek: 'Monday', periodNumber: 1, startTime: '09:00 AM', endTime: '10:15 AM', subjectName: 'Data Structures & Algorithms', teacherName: 'Dr. Elena Rostova', roomNumber: 'Lab 201' },
  { id: 'tt-2', classId: 'cls-4', className: 'B.Tech CS - Year 2', dayOfWeek: 'Monday', periodNumber: 2, startTime: '10:30 AM', endTime: '11:45 AM', subjectName: 'Advanced Applied Calculus', teacherName: 'Dr. Robert Vance', roomNumber: 'Room 204' },
  { id: 'tt-3', classId: 'cls-4', className: 'B.Tech CS - Year 2', dayOfWeek: 'Tuesday', periodNumber: 1, startTime: '09:00 AM', endTime: '10:15 AM', subjectName: 'Machine Learning Foundations', teacherName: 'Dr. Elena Rostova', roomNumber: 'Tech Annex 3B' },
  { id: 'tt-4', classId: 'cls-4', className: 'B.Tech CS - Year 2', dayOfWeek: 'Wednesday', periodNumber: 3, startTime: '01:00 PM', endTime: '02:15 PM', subjectName: 'Quantum & Wave Physics', teacherName: 'Prof. Sarah Jenkins', roomNumber: 'Science Hall 1' },
  { id: 'tt-5', classId: 'cls-4', className: 'B.Tech CS - Year 2', dayOfWeek: 'Thursday', periodNumber: 2, startTime: '10:30 AM', endTime: '11:45 AM', subjectName: 'Technical Communication', teacherName: 'Prof. Marcus Brody', roomNumber: 'Auditorium' },
  { id: 'tt-6', classId: 'cls-4', className: 'B.Tech CS - Year 2', dayOfWeek: 'Friday', periodNumber: 4, startTime: '02:30 PM', endTime: '04:00 PM', subjectName: 'AI & Capstone Project Lab', teacherName: 'Dr. Elena Rostova', roomNumber: 'Analytics Lab' },
];

export const SAMPLE_ATTENDANCE: AttendanceRecord[] = [
  { id: 'att-1', date: '2026-02-12', classId: 'cls-4', className: 'B.Tech CS - Year 2', studentId: 'std-101', studentName: 'Alexander Wright', rollNumber: 'EDU-2026-001', status: 'Present' },
  { id: 'att-2', date: '2026-02-12', classId: 'cls-4', className: 'B.Tech CS - Year 2', studentId: 'std-102', studentName: 'Sophia Chen', rollNumber: 'EDU-2026-002', status: 'Present' },
  { id: 'att-3', date: '2026-02-12', classId: 'cls-1', className: 'Grade 10-A', studentId: 'std-103', studentName: 'Lucas Moreno', rollNumber: 'EDU-2026-003', status: 'Late', remarks: 'Arrived 10 mins late (Bus delay)' },
  { id: 'att-4', date: '2026-02-12', classId: 'cls-3', className: 'Grade 11-Science', studentId: 'std-104', studentName: 'Emma Watson', rollNumber: 'EDU-2026-004', status: 'Present' },
  { id: 'att-5', date: '2026-02-12', classId: 'cls-5', className: 'B.Sc Data Science', studentId: 'std-105', studentName: 'Aarav Patel', rollNumber: 'EDU-2026-005', status: 'Present' },
];

export const SAMPLE_COURSES: CourseProgram[] = [
  {
    id: 'crs-1',
    title: 'Bachelor of Technology in Computer Science & AI',
    code: 'B.Tech CS-AI',
    degree: 'Undergraduate Degree',
    duration: '4 Years (8 Semesters)',
    department: 'Computer Science',
    description: 'Specialization in artificial intelligence, software engineering, cloud computing, and big data architectures.',
    iconName: 'Cpu',
    totalStudents: 340,
  },
  {
    id: 'crs-2',
    title: 'B.Sc. Data Science & Business Analytics',
    code: 'B.Sc DS',
    degree: 'Undergraduate Degree',
    duration: '3 Years (6 Semesters)',
    department: 'Data Analytics',
    description: 'Comprehensive curriculum focusing on predictive modeling, statistics, python data stack, and business intelligence.',
    iconName: 'BarChart3',
    totalStudents: 210,
  },
  {
    id: 'crs-3',
    title: 'Advanced High School Senior STEM Track',
    code: 'HS-STEM',
    degree: 'Diploma Certificate',
    duration: '2 Years',
    department: 'Secondary Education',
    description: 'Pre-university preparation in honors Physics, Calculus, Chemistry, and AP Computer Science Principles.',
    iconName: 'GraduationCap',
    totalStudents: 480,
  },
  {
    id: 'crs-4',
    title: 'Master of Science in Cybersecurity & Cloud',
    code: 'M.Sc CS',
    degree: 'Postgraduate Degree',
    duration: '2 Years',
    department: 'Cyber Security',
    description: 'Advanced enterprise threat analysis, network defense, cryptography, and serverless infrastructure engineering.',
    iconName: 'ShieldCheck',
    totalStudents: 150,
  },
];

export const SAMPLE_TESTIMONIALS: Testimonial[] = [
  {
    id: 'tst-1',
    name: 'Dr. Rebecca Vance',
    role: 'Parent of High School Senior',
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
    quote: 'EduFlow SIS completely transformed how our family stays connected with school activities. Instant attendance alerts, fee receipts, and real-time report cards give us total peace of mind.',
    rating: 5,
  },
  {
    id: 'tst-2',
    name: 'Prof. David Lawson',
    role: 'Head of Mathematics Department',
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=150&q=80',
    quote: 'As a teacher managing 120+ students across multiple sections, EduFlow saves me hours every week on grading, attendance, and timetable coordination. The intuitive interface is unmatched.',
    rating: 5,
  },
  {
    id: 'tst-3',
    name: 'Sophia Chen',
    role: 'Computer Science Scholar',
    image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=150&q=80',
    quote: 'Having all my course materials, exam schedules, GPA analytics, and timetable in one mobile-responsive dashboard makes organizing my academic life effortless!',
    rating: 5,
  },
];
